version: "3"
services:
  e2e:
    build: ./e2e
    depends_on:
      - service
      - client
    environment:
      - CYPRESS_baseUrl=http://client:3000
    command: > 
      sh -c "wait-on http://service:8000/status http://client:3000 && npx cypress run"
  service:
    command: >
      sh -c "
        wait-on http://prisma:${PRISMA_PORT} && 
        npm run prisma:deploy --force &&
        npm run worker:seed &&
        npm start
      "
