version: "3"
services:
  e2e:
    build: ./e2e
    depends_on:
      - graphql_service
      - client
    environment:
      - CYPRESS_baseUrl=http://client:3000
    command: > 
      sh -c "wait-on http://graphql_service:8000/status http://client:3000 && npx cypress run"
