version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.24.0
        environment:
          TERM: xterm # enables colors in the output
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build images
          command: sh test.sh build
      - run: 
          name: Run Test
          command: sh test.sh
workflows:
  build:
    jobs:
    - build
  version: 2
