version: "3.7"
services:
  postgres:
    container_name: re-radio_postgres
    image: postgres:10.8-alpine
    restart: "no"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
    container_name: re-radio_pgadmin
    image: dpage/pgadmin4:4.13
    restart: "no"
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
