version: '3'
services:
  service:
    container_name: re-radio_service
    build:
      context: .
      args:
        PRISMA_VERSION: ${PRISMA_VERSION}
    ports:
      - "8000:8000"
    command: >
      sh -c "
        npm run build &&
        wait-on http://prisma:${PRISMA_PORT} && 
        npm start
      "
