version: "3.7"
services:
  prisma:
    container_name: re-radio_prisma
    image: prismagraphql/prisma:1.33.0
    restart: "no"
    depends_on: [db]
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: postgres
            host: ${DB_HOST}
            port: ${DB_PORT}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true
  db:
    container_name: re-radio_db
    image: postgres:10-alpine
    restart: "no"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
