version: "3.7"
services:
  graphql_service:
    container_name: re-radio_graphql_service
    restart: ${RESTART_POLICY}
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:8000"
    command: >
      npx npm-run-all --parallel start:graphql seed
    environment:
      - "CI=1"
      - "NODE_ENV=production"
      - "DB_HOST=re-radio_postgres"
      - "REDIS_HOST=re-radio_redis"
      - "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}"
  real-time_service:
    container_name: re-radio_real-time_service
    restart: ${RESTART_POLICY}
    build:
      context: ./server
    command: >
      npm run start:real-time
    environment:
      - "CI=1"
      - "NODE_ENV=production"
      - "DB_HOST=re-radio_postgres"
      - "REDIS_HOST=re-radio_redis"
      - "RADIO_SERVER_HOST=re-radio_graphql_service"
      - "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}"
  client:
    container_name: re-radio_client
    restart: ${RESTART_POLICY}
    build:
      context: ./client
      target: bundle-stage
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - "CI=1"
      - "NODE_ENV=production"
